apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  selector:
    app: resume-app
  ports:
    - protocol: TCP
      port: 80     # External access port
      targetPort: 5000  # Flask app port inside the container
  type: LoadBalancer  
